FROM golang:latest as builder
COPY . /app/.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./app


FROM alpine:latest  
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"] 
