apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: myapp
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: posts-service
      taskRef:
        name: build-docker
      params:
        - name: BUILDER_IMAGE
          value: posts-service
     - name: build
      taskRef:
        name: editor-service           
      params:
        - name: BUILDER_IMAGE
          value: editor-service           
      resources:
        inputs:
          - name: source
            resource: source
